---
yamlFileName: 2015-02-01-openWeatherMap.Rmd # WARNING: update the filename?
# print(rmarkdown::metadata$yamlFileName) # permalink
# library(knitr)
# setwd("~/git/ttmmghmm.github.io/_posts") ; fn <- "2015-02-01-openWeatherMap.Rmd" ; knit(fn)  # to get the .md file 
#
# library(knitrBootstrap)
# rmarkdown::render(fn, knitrBootstrap::bootstrap_document(), clean = FALSE) # no md?
# produce an identical result to Knit HTML in RStudio- no run-time dependency on RStudio
# https://github.com/jimhester/knitrBootstrap#bootstrap-themes
#   knit(fn) ; markdownToHTML("foo.md") ; browseURL("foo.html")
# pandoc(fn, format = "docx") # prodces the .docx file - Word doc.
# rmarkdown::render(fn) # produces table of contents (and html?)
# rmarkdown::render(fn, pdf_document()) # and knit2html() to get .html from .md
title: "sparkline"
#
# like categories, tags can be specified as a YAML list or a space- separated string.
# http://en.wikipedia.org/wiki/YAML#Lists
type: posts
layout: post
tags: openWeatherMap R 
categories: rstats openWeatherMap
output:
  # https://github.com/jimhester/knitrBootstrap
  # http://cran.r-project.org/web/packages/knitrBootstrap/README.html
  # ::bootstrap_document custom rendering function for the Rmarkdown package.
  knitrBootstrap::bootstrap_document: #  to create bootstrap styled HTML reports - not .md
    # https://github.com/jimhester/knitrBootstrap#package-options
    # title: "where does this appear? # (NULL) Set the title for the html document
    # http://bootswatch.com/ optionally including a dynamic style switch.
    theme: cerulean # Cyborg # monokai cyborg slate darkly superhero cerulean 
    theme.chooser: TRUE # (FALSE) - Add a bootstrap style chooser to the page.
    # highlight Set the default code style. (HighlightJS)
    # https://github.com/jimhester/knitrBootstrap#highlight-themes
    highlight: Zenburn # monokai # Sunburst # Zenburn # HighlightJs # google code 
    highlight.chooser: TRUE # (FALSE) - Add a code style chooser to the page.
    menu: TRUE # FALSE # Whether to include the bottom navbar.
author: ttmmghmm
---

========================================================


```{r, eval = FAL}
library(devtools)
# install_github("RODProt", "QBRC")
library(RODProt)
myUrl <- "http://raw.github.com/QBRC/RODProt/4f401d0773bcfa613c6640fad8cce356b28ecf95/inst/extdata/mixed.json"
str(read_json_table(myUrl))
```

OpenStreetMap package

```{r}
cityName <- "London"
(myUrl <- paste0("http://api.openweathermap.org/data/2.5/history/city?q=",
  cityName, "&type=hour&start=1369728000&cnt=3", collapse = ""))
library(RCurl)
dat <- RCurl::getURL(myUrl)
str(dat)
df <- rjson::fromJSON(dat)
meta  <- unlist(df[names(df) != "list"])
str(df$list[[2]])
sapply(, length)
(df2 <- data.frame(do.call("rbind" , 
  lapply(df$list, function(ii) unlist(lapply(ii, data.frame)))
  )))
indTimeCol <- grep("^dt", names(df2))
library(xts)
df3 <- xts(df2[-indTimeCol], index = df2[indTimeCol])

x <- df$list[[1]]
lapply(x, unlist, rec = F)
xTimes  <- unlist(lapply(df$list, "[[", "dt"))
as.POSIXct(xTimes, origin="1970-01-01")
str(x)
names(x)
date(x$dt)
as.POSIXct(x$dt, origin="1970-01-01")

df <- JSONtoDF(jsonStr = dat)
do.call(rbind.data.frame, df$list[1])

library(d3Network)
library(RJSONIO)
packageDescription('RJSONIO')
fromJSON



# Or to get some more traditional CSV data as it might exist in the Simple Data Format:
pkg <- read_data_package("http://raw.github.com/datasets/house-prices-us/0b5042bbe9a2c2537a3bd708287321396b534710/datapackage.json")
file <- get_resource(pkg, "national", overlook.types=TRUE)
#  overlook.types parameter must be set to TRUE if you're attempting to load a file that has an unsupported data type (such as date)
 
 
library(RODProt)
pkg <- read_data_package("http://data.okfn.org/data/cpi/datapackage.json")
cpi <- get_resource(pkg, "cpi.csv", overlook.types=TRUE)
head(cpi)
 
```


http://data.okfn.org/data
 
https://github.com/QBRC/RODProt
 
http://data.okfn.org/data 
 
https://github.com/mylesmharrison/WTI_ON_gasprices
 
http://okfnlabs.org/blog/2014/09/11/data-api-for-data-packages-with-dpm-and-ckan.html
 

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(cars)
```

