---
yamlFileName: 2015-01-27-bitcoin.Rmd # WARNING: update the filename?
# print(rmarkdown::metadata$yamlFileName) # permalink
# library(knitr)
# setwd("~/git/ttmmghmm.github.io/_posts") ; fn <- "2015-01-10-sparkline.Rmd" ; knit(fn)  # to get the .md file 
#
# library(knitrBootstrap)
# rmarkdown::render(fn, knitrBootstrap::bootstrap_document(), clean = FALSE) # no md?
# produce an identical result to Knit HTML in RStudio- no run-time dependency on RStudio
# https://github.com/jimhester/knitrBootstrap#bootstrap-themes
#   knit(fn) ; markdownToHTML("foo.md") ; browseURL("foo.html")
# pandoc(fn, format = "docx") # prodces the .docx file - Word doc.
# rmarkdown::render(fn) # produces table of contents (and html?)
# rmarkdown::render(fn, pdf_document()) # and knit2html() to get .html from .md
title: "stochvolR example"
#
# like categories, tags can be specified as a YAML list or a space- separated string.
# http://en.wikipedia.org/wiki/YAML#Lists
type: posts
layout: post
tags: R bitcoin
categories: rstats bitcoin
output:
  # https://github.com/jimhester/knitrBootstrap
  # http://cran.r-project.org/web/packages/knitrBootstrap/README.html
  # ::bootstrap_document custom rendering function for the Rmarkdown package.
  knitrBootstrap::bootstrap_document: #  to create bootstrap styled HTML reports - not .md
    # https://github.com/jimhester/knitrBootstrap#package-options
    title: where does this appear? # (NULL) Set the title for the html document
    # http://bootswatch.com/ optionally including a dynamic style switch.
    theme: Cyborg # cerulean # Cyborg # monokai cyborg slate darkly superhero cerulean 
    theme.chooser: TRUE # (FALSE) - Add a bootstrap style chooser to the page.
    # highlight Set the default code style. (HighlightJS)
    # https://github.com/jimhester/knitrBootstrap#highlight-themes
    highlight: monokai # Zenburn # monokai # Sunburst # Zenburn # HighlightJs # google code 
    highlight.chooser: TRUE # (FALSE) - Add a code style chooser to the page.
    menu: TRUE # FALSE # Whether to include the bottom navbar.
author: ttmmghmm
---
```{r child = c('../_posts/boiler_plate_vignette_setup.Rmd', '../_posts/boiler_plate_bibliography_start.Rmd') }
# child: (NULL; character) a character vector of filenames of child documents to be run and input into the main document http://yihui.name/knitr/options/
# http://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output
require(knitr)
opts_chunk$set(cache = TRUE)
```

# Bitcoin
* <http://beautifuldata.net/2015/01/querying-the-bitcoin-blockchain-with-r>

```{r}
library(devtools)
devtools::install_github("Rdatatable/data.table") # , build_vignettes=FALSE)
# library(data.table)
install_github('jangorecki/Rbitcoin')
```

```{r Rbitcoin}
library(Rbitcoin)
library(magrittr)
```

##  aggregated values
```{r}
# no need for antiddos function anymore as it is now built-in every web call
# wait <- antiddos(market = 'kraken', antispam_interval = 5, verbose = 1)
market.api.process('kraken',c('BTC','EUR'),'ticker')
```
```{r}
trades <- market.api.process(market = 'kraken', curr = c('BTC', 'EUR'), action = 'trades'
  , verbose = T # getOption("Rbitcoin.verbose", 0),
)
str(trades)
trades  %>% extract('trades') %>% head
# Instead of Rbitcoin.plot use rbtc.plot
rbtc.plot(trades, col='blue')
```

# download and transform the blockchain data
Read every single transaction in the history of Bitcoin?

* query historical transactions for one address
```{r}
wallet <- blockchain.api.process('15Mb2QcgF3XDMeVn6M7oCG6CQLw4mkedDi')
seed <- '1NfRMkhm5vjizzqkp2Qb28N7geRQCa4XqC'
genesis <- '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
singleaddress <- blockchain.api.query(
  method = 'Single Address', 
  bitcoin_address = seed, 
  limit = 1e2)
txs <- singleaddress$txs
#txs[1][[1]]
#txs %>% str %>% extract2(1)
length(txs)
```

* map the connections between all addresses in this strand of the Blockchain
```{r}
bc <- data.frame()
#txs %>%
#  (extract2('hash') -> hash) %>%
#  (extract2('inputs') -> inputs)
 
for (t in txs) {
  hash <- t$hash
  for (inputs in t$inputs) {
    from <- inputs$prev_out$addr
    for (out in t$out) {
      to <- out$addr
      va <- out$value
      bc <- rbind(bc, data.frame(from=from,to=to,value=va, stringsAsFactors=F))
    }
  }
}
bc %>% str
bc %>% tail
```

```{r}
library(dplyr)
data_frame
bc %>% 
  group_by(from, to) %>% 
  summarise(value = sum(value)) -> 
  btc 
```

Finally, we’re using igraph to calculate and draw the resulting network of transactions between addresses:

```{r}
library(igraph)
btc.net <- graph.data.frame(btc, directed=T)
V(btc.net)$color <- "blue"
V(btc.net)$color[unlist(V(btc.net)$name) == seed] <- "red"
nodes <- unlist(V(btc.net)$name)
E(btc.net)$width <- log(E(btc.net)$value)/10
plot.igraph(btc.net, vertex.size=5, edge.arrow.size=0.1, vertex.label=NA, main=paste("BTC transaction network for\n", seed))
```

```{r child = c('../_posts/boiler_plate_reproducibility.Rmd', '../_posts/boiler_plate_bibliography_end.Rmd') }
```
